import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
import { Footer, FireFilesbg } from '@/components/index'
import { icons } from 'lucide-react'

export const metadata = {
  title: 'Ivy Rong blog',
  description: 'Generated by Ivy Rong blog',
  icon: '/cat.png'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={(clsx(inter.variable), 'bg-background text-foreground')}>
        <div className="relative">
          {children}
          <FireFilesbg />

          <Footer />
        </div>
      </body>
    </html>
  )
}
